# Note: supported platforms: macOS, Linux and Windows
# Please make sure that's working on all supported platforms
version: "3.9"

services:
  web:
    build: ./app
    restart: always
    command: bash -c "python main.py"
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - postgres
  #      - redis
  #      - rabbitmq
  #      - elasticsearch
  postgres:
    image: postgres:12.8-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    env_file:
      - ./.env
#  redis:
#    image: redis:5.0-alpine
#    restart: always
#  rabbitmq:
#    image: rabbitmq:3.8.14-alpine
#    restart: always
#  elasticsearch:
#    image: elasticsearch:2.4.6-alpine
#    restart: always
volumes:
  postgres_data: